[build]
  publish = "dist"
  command = "npm run build"

[[redirects]]
  from = "/api/*"
  to = "https://unadministratively-instable-tawana.ngrok-free.dev/api/:splat"
  status = 200
  force = true
  headers = {X-From = "Netlify"}

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
